### ISSUE TITLE
Akka persistence not working on 2.4.2_RC1

### ISSUE THREAD

**Issue by yoseldvp** [akka/akka-persistence-cassandra#37]
I just migrated to the new version of the plugin using the new version of akka, and i'm getting a class not found exception.

I'm using Java 1.8, with akka 2.4.2_RC1 and the 0.7 version of the akka-persistence-cassandra plugin

```
Caused by: java.lang.NoClassDefFoundError: akka/stream/scaladsl/ImplicitMaterializer
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(ReflectiveDynamicAccess.scala:21)
	at akka.actor.ReflectiveDynamicAccess$$anonfun$getClassFor$1.apply(ReflectiveDynamicAccess.scala:20)
	at scala.util.Try$.apply(Try.scala:192)
	at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:20)
	at akka.persistence.Persistence.akka$persistence$Persistence$$createPlugin(Persistence.scala:274)
	at akka.persistence.Persistence$PluginHolderExtensionId.createExtension(Persistence.scala:300)
	at akka.persistence.Persistence$PluginHolderExtensionId.createExtension(Persistence.scala:294)
	at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:757)
	at akka.actor.ExtensionId$class.apply(Extension.scala:79)
	at akka.persistence.Persistence$PluginHolderExtensionId.apply(Persistence.scala:294)
	at akka.persistence.Persistence.pluginHolderFor(Persistence.scala:258)
	at akka.persistence.Persistence.journalConfigFor(Persistence.scala:214)
	at akka.persistence.Eventsourced$class.$init$(Eventsourced.scala:54)
	at akka.persistence.UntypedPersistentActor.<init>(PersistentActor.scala:111)
	at com.xtiva.poc.akka.command.codes.CodesAggregate.<init>(CodesAggregate.java:40)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	... 16 more
Caused by: java.lang.ClassNotFoundException: akka.stream.scaladsl.ImplicitMaterializer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 59 more
```

**Comment by patriknw** [comment]
In short: try version 0.8 that was build for Akka 2.4.2-RC1, see README for instructions.

That is expected. 0.7 was for the persistence-query-experimental api that was defined by Akka 2.4.1, using akka-stream-experimental 1.0. Akka 2.4.2-RC1 includes latest akka-stream with changed api, and therefore changed persistence-query-experimental.
